### ISSUE TITLE
Error: Closing file descriptor 25 on garbage collection

### ISSUE THREAD

**Issue by abhishekOptiphoenix** [awsmin/f1#9]
I loved your project and building a massive project with that but When I clone your repo and try to add this package `npm i @frontity/google-analytics` . It shows the below error: 

![Screenshot 2022-06-29 at 12 16 40 PM](https://user-images.githubusercontent.com/97602173/176372536-a84f2f86-454a-4a64-a344-28a774ba5fa0.png)
![Screenshot 2022-06-29 at 12 28 35 PM](https://user-images.githubusercontent.com/97602173/176372575-5dee6817-22ee-4306-b850-b4682a545469.png)

and this also happens when trying to add `npm i @frontity/google-tag-manager-analytics` and `npm i @frontity/wp-comments` or try to update the frontity dependencies.

**Comment by VinuRaj** [comment]
This seems to be due to an outdated node installed on your machine. Try using the recommended version of node and reinstall the node_modules in the Frontity project (delete the existing node_modules and package-lock.json file)

Steps - https://docs.frontity.org/guides/keep-frontity-updated#troubleshooting

Fixes from Frontity community -

https://community.frontity.org/t/frontity-dev-command-error-closing-file-descriptor-25/5715
https://community.frontity.org/t/npx-frontity-dev-suddenly-not-working/5101/2

**Comment by abhishekOptiphoenix** [comment]
I did all the things you mentioned above and it's working fine but now I found the same error when a installed`https://www.npmjs.com/package/frontity-contact-form-7` this plugin. Is there anything which conflicts between versions?

**Comment by VinuRaj** [comment]
It seems the package is not maintained and have some issue with the latest Frontity/ WordPress.

You could find another forked version out here, which seems to be maintained and working with the latest Frontity/ WordPress.
https://github.com/imranhsayed/frontity-contact-form-7/issues/48
